apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment-annotator-controller.fullname" . }}-config
  labels:
    {{- include "deployment-annotator-controller.labels" . | nindent 4 }}
data:
  GRAFANA_URL: {{ .Values.grafana.url | quote }}
  WATCH_DEPLOYMENTS: {{ .Values.controller.watch.deployments | quote }}
  WATCH_STATEFULSETS: {{ .Values.controller.watch.statefulSets | quote }}
  WATCH_DAEMONSETS: {{ .Values.controller.watch.daemonSets | quote }}
