apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployment-annotator-controller.fullname" . }}-grafana
  labels:
    {{- include "deployment-annotator-controller.labels" . | nindent 4 }}
type: Opaque
data:
  GRAFANA_API_KEY: {{ .Values.grafana.apiKey | b64enc }}
