apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment-annotator-controller.fullname" . }}
  labels:
    {{- include "deployment-annotator-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.healthPort | default 8080 }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.service.metricsPort | default 8081 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "deployment-annotator-controller.selectorLabels" . | nindent 4 }}
